# Config de Red
IP=127.0.0.1

# Config de los puertos 
Registro_to_Server=6000
PUERTO_CONFIRMACION=7000
Server_to_Pantalla=5000
Server_to_Empleado_base=4050
Empleado_to_Server=5050
Empleado_to_Server2=5051
Registro_to_Server2=6001
Server_to_Server2=2000
Server2_to_Server=2001

Formato = JSON